apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpt-admission-webhook.fullname" . }}-token
  labels:
    {{- include "gpt-admission-webhook.labels" . | nindent 4 }}
data:
  token: {{ .Values.openAI.apiKey | b64enc }}